# Generated by Django 5.1.5 on 2025-02-05 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postmodel",
            options={"ordering": ("-date_created",)},
        ),
    ]
